#!/usr/bin/env bash

build() {
  rm -r dist/* 2>/dev/null
  babel --presets es2015,stage-0 lib --out-dir dist --ignore lib/secrets.js
  cp lib/secrets.js dist
}

test() {
  ./test.js
}

publish() {
  npm publish
}

case "$1" in
  b | build) build ;;
  t | test) test ;;
  p | publish ) publish ;;
esac
