#!/usr/bin/env bash

main() {
  build
}

build() {
  rm -r lib 2>/dev/null
  babel src --out-dir lib
}

test() {
  ./test.js
}

publish() {
  npm publish
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
  t | test) test ;;
  p | publish ) publish ;;
esac
